http:
  port: 8061
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'

  persons:
    host: localhost
    paths: '/persons'
  getPerson:
    host: localhost
    paths: '/person/:id'
  postPerson:
    host: localhost
    paths: '/person'

  users:
    host: localhost
    paths: '/users'
  user:
    host: localhost
    paths: '/user/:id'
  postUser:
    host: localhost
    paths: '/user'

  commends-property:
    host: localhost
    paths: '/commends-property'
  commend-property:
    host: localhost
    paths: '/commend-property/:id'
  post-commend-property:
    host: localhost
    paths: '/commend-property'

  commends-user:
    host: localhost
    paths: '/commends-user'
  commend-user:
    host: localhost
    paths: '/commend-user/:id'
  postCommendUser:
    host: localhost
    paths: '/commend-user-create'

  commendsUserProperty:
    host: localhost
    paths: '/users-properties/:id'

  postTransaction:
    host: localhost
    paths: '/transaction'
  postMethodPayment:
    host: localhost
    paths: '/method-payment'
  getAllTransactions:
    host: localhost
    paths: '/transactions'
  getAllMethodsPayments:
    host: localhost
    paths: '/methods-payments'

  postTypeProperty:
    host: localhost
    paths: '/type-property'
  postProperty:
    host: localhost
    paths: '/property'
  postCheckin:
    host: localhost
    paths: '/checkin'
  getProperties:
    host: localhost
    paths: '/properties'


serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - body-parser
  - create-person
  - get-person
  - get-users
  - get-user
  - get-commends-property
  - get-commends-user
  - get-commend-property
  - get-commend-user
  - post-person
  - post-user
  - post-commend-property
  - post-commend-user
  - commeds-user
  - create-transaction
  - create-method-payment
  - get-transactions
  - get-methods-payments
  - create-type-property
  - create-property
  - create-checkin
  - get-properties
customPolicies:
  - myCustomPolicy: './create-person-policy.js'
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

  personPipeline:
    apiEndpoints:
      - persons
    policies:
      - create-person: 
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/persons']
  getPersonPipeline:
    apiEndpoints:
      - getPerson
    policies:
      - get-person:
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/person']
  postPersonPipeline:
    apiEndpoints:
      - postPerson
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - post-person:
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/person/create']

  usersPipeline:
    apiEndpoints:
      - users
    policies:
      - get-users: 
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/get-all-users']
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - get-user: 
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/get-user']
  postUserPipeline:
    apiEndpoints:
      - postUser
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - post-user:
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/create']


  commendsPropertyPipeline:
    apiEndpoints:
      - commends-property
    policies:
      - get-commends-property: 
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/commends']
  commendPropertyPipeline:
    apiEndpoints:
      - commend-property
    policies:
      - get-commend-property: 
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/commend']
  postCommendPropertyPipeline:
    apiEndpoints:
      - post-commend-property
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - post-commend-property:
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/commend/create']

  commendsUserPipeline:
    apiEndpoints:
      - commends-user
    policies:
      - get-commends-user: 
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/commends-person']
  commendUserPipeline:
    apiEndpoints:
      - commend-user
    policies:
      - get-commend-user: 
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/commend-person']
  postCommendUserPipeline:
    apiEndpoints:
      - postCommendUser
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - post-commend-user:
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/commend-person/create']

  getCommendsUserPropertiesPipeline:
    apiEndpoints:
      - commendsUserProperty
    policies:
      - commeds-user:
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8083/commends', 'http://localhost:8083/commends-person']

  postTransactionPipeline:
    apiEndpoints:
      - postTransaction
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - create-transaction:
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8084/transacction/create']
  postMethodPaymentPipeline:
    apiEndpoints:
      - postMethodPayment
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - create-transaction:
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8084/metodopago/create']  
  transactionsPipeline:
    apiEndpoints:
      - getAllTransactions
    policies:
      - get-transactions: 
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8084/transacction-list'] 
  methodsPaymentsPipeline:
    apiEndpoints:
      - getAllMethodsPayments
    policies:
      - get-methods-payments: 
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8084/metodopago-list']  

  postTypePropertyPipeline:
    apiEndpoints:
      - postTypeProperty
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - create-type-property:
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8082/create']  
  postPropertyPipeline:
    apiEndpoints:
      - postProperty
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - create-property:
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8082/create-propiedad']
  postCheckinPipeline:
    apiEndpoints:
      - postCheckin
    policies:
      - body-parser:
          - action:
              json:
                strict: false
      - create-checkin:
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8082/create-checkin']   
  propertiesPipeline:
    apiEndpoints:
      - getProperties
    policies:
      - get-properties: 
          - action:
              changeOrigin: true
              baseUrl: ['http://localhost:8082/propiedades']     

    
