# Core
db:
  redis:
    emulate: true
    namespace: EG

plugins:
   express-gateway-plugin-body-parser: {}
   myCustomPolicy:
     package: './plugins/manifest.js'
   myCustomPolicy2:
     package: './plugins/manifest1.js'
   myCustomPolicy3:
     package: './plugins/manifest-users.js'
   myCustomPolicy4:
     package: './plugins/manifest-user.js'
   myCustomPolicy5:
     package: './plugins/manifest-commends-property.js'   
   myCustomPolicy7:
     package: './plugins/manifest-commends-user.js'
   myCustomPolicy8:
     package: './plugins/manifest-commend-property.js'
   myCustomPolicy9:
     package: './plugins/manifest-commend-user.js'
   myCustomPolicy10:
     package: './plugins/manifest-create-person.js'
   myCustomPolicy11:
     package: './plugins/manifest-create-user.js'
   myCustomPolicy12:
     package: './plugins/manifest-create-commend-property.js'
   myCustomPolicy13:
     package: './plugins/manifest-create-commend-user.js'
   myCustomPolicy14:
     package: './aggregators/plugins/commend-aggregate.js'
   myCustomPolicy15:
     package: './method-payment/plugins/create-transaction.js'
   myCustomPolicy16:
     package: './method-payment/plugins/method-payment.js'
   myCustomPolicy17:
     package: './method-payment/plugins/get-transactions.js'
   myCustomPolicy18:
     package: './method-payment/plugins/get-methods-payments.js'

   myCustomPolicy19:
     package: './properties/plugins/create-type-property.js'
   myCustomPolicy20:
     package: './properties/plugins/create-property.js'
   myCustomPolicy21:
     package: './properties/plugins/create-checkin.js'
   myCustomPolicy22:
     package: './properties/plugins/get-properties.js'
crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
